{{- if .Values.deployClusterServiceBroker }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: broker-skeleton
spec:
  url: https://{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  insecureSkipTLSVerify: true
#  authInfo:
#    bearer:
#      secretRef:
#        namespace: {{.Release.Namespace}}
#        name: {{ template "fullname" . }}
{{- end }}
