---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-service
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}--{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.authenticate}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-client
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}--{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "fullname" . }}-service
    namespace: {{ .Release.Name }}
roleRef:
  kind: ClusterRole
  name: {{ template "fullname" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  annotations:
    kubernetes.io/service-account.name: {{ template "fullname" . }}-client
type: kubernetes.io/service-account-token
{{- end }}
